source 'https://rubygems.org' # where to look for gems
gem "sinatra",   "~> 1.2.6"   # our web framework
gem "rdiscount", "~> 1.6.8"   # allows Sinatra to render markdown
gem "shotgun", "~> 0.9.2" # Allows me to make changes without restarting server.
